# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # Filters
    filter_sets:

        # name our filter set "my_fixed_filter"
        carousel_filter:
            filters:
                 # use and setup the "relative_resize" filter
                relative_resize:
                    # given 50x40px, output 32x26px using "widen" option
                    widen: 400

        artist_filter:
            filters:
                relative_resize:
                    widen: 546

        contact_filter:
            filters:
                # use and setup the "relative_resize" filter
                relative_resize:
                    # given 50x40px, output 75x60px using "heighten" option
                    widen: 756
